### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by connor557** [kxes/boottotheweb#1]
What is this and how does it work? It looks kinda cool.

**Comment by joshiggins** [comment]
It's a work in progress but the idea was to have something that could boot from PXE/USB/whatever and download the OS over HTTP, being a bit more flexible than gpxe/ipxe etc.

There is also a script for Ubuntu's initramfs that will download a squashfs root image over HTTP.

If you are interested I can make a how to for test it :)

**Comment by connor557** [comment]
I am very interested. I have a terminal server and I would like a solution to distribute a golden image of a thin client os and then connect to my terminal server from there.

**Comment by connor557** [comment]
Are you still developing this system?

**Comment by joshiggins** [comment]
Wow, a month goes so fast. Yes but it needs more time than I can spend on it at the moment. 

1. you need to copy the `boottotheweb` script into an Ubuntu initramfs in `/scripts/boottotheweb`
2. you supply the following parameters 
```boot=boottotheweb server=1.2.3.4 filename=filesystem.squashfs```
3. arrange for a PXE server or something to boot a kernel with the modified initramfs

You can pinch the squashed filesystem from the Ubuntu live CD for testing. It will download the squash to RAM and then boot it. Then you figure out how to make your own squash filesystem! ;)

Really, this should be a distribution-independent initramfs loader that is served with a kernel+filesystem combination. But now you sparked my interest again so maybe it will get some updates.

**Comment by connor557** [comment]
Well thank you, but my use case would be using this as an alternative to PXE boot. See, I have a server I call the "mainframe" that sits out in a datacenter and serves up my website and floating desktops. The server is not on the same network as the computers I would like to PXE, therefore I cannot PXE the pinched ltsp client to my workstations.
